version: '3'
services:
  db-rewind-container:
    build:
      context: './'
      args: 
        - DB_REWINDER_POSTGRES_VERSION=$DB_REWINDER_POSTGRES_VERSION
      dockerfile: 'dockerfile'
    volumes:
      - ../:/opt/db_rewind