# Use an official Ubuntu as a parent image
FROM ubuntu:22.04

# Set environment variables to non-interactive for automated installs
ENV DEBIAN_FRONTEND=noninteractive

# Update the package list and install prerequisites
RUN apt-get update && \
    apt-get install -y software-properties-common

# Install curl
RUN apt-get install -y curl ca-certificates

# Add postgres repository.
####################
RUN apt-get install -y postgresql-common
RUN yes | /usr/share/postgresql-common/pgdg/apt.postgresql.org.sh

RUN install -d /usr/share/postgresql-common/pgdg
RUN curl -o /usr/share/postgresql-common/pgdg/apt.postgresql.org.asc --fail https://www.postgresql.org/media/keys/ACCC4CF8.asc
RUN sh -c 'echo "deb [signed-by=/usr/share/postgresql-common/pgdg/apt.postgresql.org.asc] https://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'

RUN apt-get update

####################


# Install Python3, Git, and PostgreSQL
RUN apt-get update && \
    apt-get install -y python3 python3-pip git postgresql-12 postgresql-client-12


# Define the entrypoint script to run
ENTRYPOINT ["/opt/db_rewind/build_tests/src/entrypoint.sh"]
