# .github/workflows/docker-compose.yml
name: build app test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Build Docker image
      run: docker-compose -f './build_tests/docker-compose.yml' build

    - name: Run E2E test
      run: |
        chmod +x './build_tests/github-workflow-runner.sh';
        bash ./build_tests/github-workflow-runner.sh;
        exit $?;
